### ISSUE TITLE
Test.kt should be seperated from kotlin-lib

### ISSUE THREAD

**Issue by Doomsdayrs** [shosetsuorg/kotlin-lib#28]
Currently, `Test.kt` is dependent on kotlin-lib, and creates this weird use case of it being in the test directory (which is used for testing the actual code of the repository).

@TechnoJo4 , Do you agree with separating it to its own repository?

**Comment by TechnoJo4** [comment]
Not right now, no. It'd create a repository with a single file and the dependency would be hard to manage (has to somehow be able to depend on an entirely local version of kotlin-lib outside the repository).

**Comment by Doomsdayrs** [comment]
@TechnoJo4 Not at all, It has already been created: https://github.com/shosetsuorg/extension-tester

**Comment by Doomsdayrs** [comment]
This allows us to update the tester without being dependent on kotlin-lib

**Comment by Doomsdayrs** [comment]
Has been completed.
