### ISSUE TITLE
Add startIndex to Extensions 

### ISSUE THREAD

**Issue by Doomsdayrs** [shosetsuorg/kotlin-lib#35]
Add a `startIndex` integer to Extensions.

This `startIndex` will be defaulted to 0

Developers have the option to override and set it to 1 if the website is programmed in that way.

**Comment by Dunbock** [comment]
Why is the default 0, when it should clearly be 1? The number of websites that use page 0, which does not equal page 1, is utterly insignificant if they even exist in the first place. Like basically every website that does paging starts with page 1, I am not even aware of a website starting at 0. Can you give multiple examples of applicable websites please, where that is the case.

Also it is a bit unclear to me if the start index is incrementing listings and / or incrementing search. I assume it is for both, but as I know of no such website I do not see a guarantee that they couldn't be implemented differently.
